name: Snake Game

on:
  # Atualizado para usar a versão mais recente do cron
  schedule:
    - cron: "0 */5 * * *"
  # Permitir a execução manual da action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Corrigido o nome do repositório na configuração
      - name: Snake animation
        uses: Platane/snk@master
        with:
          # Corrigido o nome do usuário do GitHub
          github_user_name: StyflerRick
          # Corrigido o caminho de saída do arquivo gif
          output_dir: dist

      - name: Create gif from svg
        run: |
          cd dist
          # Adicionado o comando para gerar o arquivo gif a partir do svg
          # Instalado o pacote svg-term para conversão
          npx svg-term --in-file github-contribution-grid-snake.svg --out-file github-contribution-grid-snake.gif --no-cursor

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4.13.0
        with:
          commit_message: Update snake animation
          commit_options: '--no-verify'
          # Atualizado o nome do branch de destino para main
          branch: main

      # Atualizada a versão da action para a mais recente
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Atualizado o nome do diretório de deploy
          publish_dir: ./dist
          # Atualizado o nome do branch de deploy
          publish_branch: gh-pages
        env:
          # Adicionada a chave do token de acesso ao GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
