name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Game files
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: StyflerRick
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Set Snake GIF path
        run: echo "SNAKE_GIF_PATH=${{ steps.snake-gif.outputs.gif_path }}" >> $GITHUB_ENV




      - name: Show Git status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
        env:
         SNAKE_GIF_PATH: ${{ env.SNAKE_GIF_PATH }}


      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
